#!/usr/bin/env ruby
require 'rubygems'
require 'English'
require 'trollop'
require 'nokogiri'
require_relative 'freshdesk'
#require 'freshdesk'
#require 'ap'

def verbose(string_to_output)
  puts string_to_output if $verbose
end
# Translate a set of Level 1-4 to freshdesk priority ids (1 being low)
def convert_rt_priority_to_freshdesk (rt_priority)
  return 1 if rt_priority.to_i == 4
  return 2 if rt_priority.to_i == 3
  return 3 if rt_priority.to_i == 2
  return 4 if rt_priority.to_i == 1
end

opts = Trollop::options do
  version "1.0"
  banner <<-EOS
  #{File.basename($0)}
  Description: Parse an exported request tracker ticket and post into freshdesk.

  Usage:
  #{File.basename($0)} [options]

  where [options] are:
  EOS
  opt :verbose, "Verbose output"
  opt :username , "Freshdesk username" , :default => "wibble"
  opt :password, "Freshdesk password" , :default => "wibble"
  opt :ticket, "Ticket to read from", :default => 'Ticket_00002.xml', :required => true
  opt :domain, "Freshdesk domain" , :default => "myorg.freshdesk.com"
end
$verbose = opts[:verbose]

doc = Nokogiri::XML(IO.read(File.expand_path(opts[:ticket])).chomp)

contents = doc.xpath("//Ticket//Transactions//Attachments//Attachment//Content")

description = ""
doc.xpath("//Ticket//Transactions//Transaction//Attachments//Attachment").each do | attachment |

  puts attachment.xpath("//ContentType")[0].content
  if attachment.xpath("//ContentType")[0].content == 'text/plain'
    puts "hit"
  end
end

exit

created_at = doc.xpath("//Ticket//Created")[0].content
email = doc.xpath("//Ticket//Creator")[0].content


customfield = doc.xpath("//CustomField//Value")

# default to low priority
priority = 1

customfield.each do |customfield|
  if customfield =~/Level (\d)/
    priority = convert_rt_priority_to_freshdesk $1
  end
end

verbose "http://#{opts[:domain]}"

client = Freshdesk.new("http://#{opts[:domain]}/", opts[:username], opts[:password] )

client.post_tickets(:email => email.to_s.downcase, :priority => priority, :source => 1, :description => description, :status => 5 ,:created_at => created_at )

sleep(10)

